title : Carl Boettiger
tagline: Theoretical ecology and evolution
author :
  name : Carl Boettiger
  email : cboettig@gmail.com
  github : cboettig
  twitter : cboettig

pygments: true 
markdown: redcarpet2 
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink"]
